[2025-02-28T19:37:40.154+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/dag_ex.py
[2025-02-28T19:37:40.158+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ex.py for tasks to queue
[2025-02-28T19:37:40.179+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:37:40.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:37:40.342+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:37:40.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ex.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ex.py", line 5, in <module>
    from operators.collect_data import Collect_data_operator
  File "/opt/airflow/dags/operators/__init__.py", line 1, in <module>
    from .. import utils
ImportError: attempted relative import beyond top-level package
[2025-02-28T19:37:40.347+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:37:40.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ex.py took 0.391 seconds
[2025-02-28T19:38:10.806+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag_ex.py
[2025-02-28T19:38:10.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ex.py for tasks to queue
[2025-02-28T19:38:10.818+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:38:10.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:38:10.847+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:38:10.840+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ex.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ex.py", line 5, in <module>
    from operators.collect_data import Collect_data_operator
  File "/opt/airflow/dags/operators/__init__.py", line 1, in <module>
    from .. import utils
ImportError: attempted relative import beyond top-level package
[2025-02-28T19:38:10.849+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:38:10.877+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ex.py took 0.080 seconds
[2025-02-28T19:38:40.991+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/dag_ex.py
[2025-02-28T19:38:40.992+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ex.py for tasks to queue
[2025-02-28T19:38:40.993+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:38:40.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:38:41.015+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:38:41.010+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ex.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ex.py", line 5, in <module>
    from operators.collect_data import Collect_data_operator
  File "/opt/airflow/dags/operators/__init__.py", line 1, in <module>
    from .. import utils
ImportError: attempted relative import beyond top-level package
[2025-02-28T19:38:41.017+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:38:41.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ex.py took 0.047 seconds
[2025-02-28T19:39:11.233+0000] {processor.py:186} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_ex.py
[2025-02-28T19:39:11.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ex.py for tasks to queue
[2025-02-28T19:39:11.236+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:39:11.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:39:11.260+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:39:11.254+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ex.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ex.py", line 5, in <module>
    from operators.collect_data import Collect_data_operator
  File "/opt/airflow/dags/operators/__init__.py", line 1, in <module>
    from .. import utils
ImportError: attempted relative import beyond top-level package
[2025-02-28T19:39:11.262+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:39:11.284+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ex.py took 0.055 seconds
[2025-02-28T19:39:41.434+0000] {processor.py:186} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_ex.py
[2025-02-28T19:39:41.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ex.py for tasks to queue
[2025-02-28T19:39:41.436+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:39:41.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:39:41.463+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:39:41.456+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ex.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ex.py", line 5, in <module>
    from operators.collect_data import Collect_data_operator
  File "/opt/airflow/dags/operators/__init__.py", line 1, in <module>
    from .. import utils
ImportError: attempted relative import beyond top-level package
[2025-02-28T19:39:41.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:39:41.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ex.py took 0.058 seconds
[2025-02-28T19:40:11.646+0000] {processor.py:186} INFO - Started process (PID=44) to work on /opt/airflow/dags/dag_ex.py
[2025-02-28T19:40:11.647+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ex.py for tasks to queue
[2025-02-28T19:40:11.648+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:40:11.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:40:11.694+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:40:11.678+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ex.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ex.py", line 5, in <module>
    from operators.collect_data import Collect_data_operator
  File "/opt/airflow/dags/operators/__init__.py", line 1, in <module>
    from .. import utils
ImportError: attempted relative import beyond top-level package
[2025-02-28T19:40:11.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:40:11.725+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ex.py took 0.086 seconds
[2025-02-28T19:40:41.847+0000] {processor.py:186} INFO - Started process (PID=45) to work on /opt/airflow/dags/dag_ex.py
[2025-02-28T19:40:41.848+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ex.py for tasks to queue
[2025-02-28T19:40:41.849+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:40:41.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:40:42.659+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:40:42.646+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ex.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ex.py", line 5, in <module>
    from operators.collect_data import Collect_data_operator
  File "/opt/airflow/dags/operators/collect_data.py", line 6, in <module>
    from utils.utils import Utils
ModuleNotFoundError: No module named 'utils'
[2025-02-28T19:40:42.666+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:40:42.693+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ex.py took 0.851 seconds
[2025-02-28T19:42:33.980+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag_ex.py
[2025-02-28T19:42:33.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ex.py for tasks to queue
[2025-02-28T19:42:33.982+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:42:33.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:42:34.613+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:42:34.606+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ex.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ex.py", line 5, in <module>
    from operators.collect_data import Collect_data_operator
  File "/opt/airflow/dags/operators/collect_data.py", line 6, in <module>
    from utils.utils import Utils
ModuleNotFoundError: No module named 'utils'
[2025-02-28T19:42:34.616+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:42:34.638+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ex.py took 0.665 seconds
[2025-02-28T19:43:04.867+0000] {processor.py:186} INFO - Started process (PID=42) to work on /opt/airflow/dags/dag_ex.py
[2025-02-28T19:43:04.868+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_ex.py for tasks to queue
[2025-02-28T19:43:04.870+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:43:04.870+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:43:05.344+0000] {logging_mixin.py:190} INFO - [2025-02-28T19:43:05.334+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_ex.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_ex.py", line 5, in <module>
    from operators.collect_data import Collect_data_operator
  File "/opt/airflow/dags/operators/collect_data.py", line 6, in <module>
    from utils.utils import Utils
ModuleNotFoundError: No module named 'utils'
[2025-02-28T19:43:05.346+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_ex.py
[2025-02-28T19:43:05.361+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_ex.py took 0.501 seconds
